language: node_js

services:
  - postgres
node_js: 
  - "stable"

install: 
  - npm install

before_script:
  - psql -c "CREATE DATABASE quickcredit_testdb;" -U postgres
  - psql -c "CREATE USER user WITH PASSWORD 'user';" -U postgres
script:
  - npm run test
  - npm run coveralls

cache:
  directories:
    - node_modules